// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8vD_2xIJbSey5diEAhu88eiLCN6h7La4',
    appId: '1:974420805687:web:28a5fb86853db3326c97b2',
    messagingSenderId: '974420805687',
    projectId: 'assignment-app-74074',
    authDomain: 'assignment-app-74074.firebaseapp.com',
    storageBucket: 'assignment-app-74074.firebasestorage.app',
    measurementId: 'G-WM7RDEYD17',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWsfujyf1BULqCeYUtFet2Yv9CKcejSjQ',
    appId: '1:974420805687:ios:10dda8b974f30fb16c97b2',
    messagingSenderId: '974420805687',
    projectId: 'assignment-app-74074',
    storageBucket: 'assignment-app-74074.firebasestorage.app',
    iosBundleId: 'com.example.assignmentApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWsfujyf1BULqCeYUtFet2Yv9CKcejSjQ',
    appId: '1:974420805687:ios:10dda8b974f30fb16c97b2',
    messagingSenderId: '974420805687',
    projectId: 'assignment-app-74074',
    storageBucket: 'assignment-app-74074.firebasestorage.app',
    iosBundleId: 'com.example.assignmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8vD_2xIJbSey5diEAhu88eiLCN6h7La4',
    appId: '1:974420805687:web:46bc64010de38c5a6c97b2',
    messagingSenderId: '974420805687',
    projectId: 'assignment-app-74074',
    authDomain: 'assignment-app-74074.firebaseapp.com',
    storageBucket: 'assignment-app-74074.firebasestorage.app',
    measurementId: 'G-Q97NTNWQ26',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG8GIWmV4Yihhx6ErIJMcK7Z4NIzqAzKQ',
    appId: '1:974420805687:android:b739f08e0840f3856c97b2',
    messagingSenderId: '974420805687',
    projectId: 'assignment-app-74074',
    storageBucket: 'assignment-app-74074.firebasestorage.app',
  );
}
